apiVersion: apps/v1
kind: Deployment
metadata:
  name: manifest-nginx-git-public
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx  
  ports:
    - protocol: TCP
      port: 82
      targetPort: 8082
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
