version: '3'
services:
 minio-server:
  image: minio/minio:latest
  ports:
   - 3000:9000
   - 3001:3001
  command: server /data --console-address ":3001"
  environment:
   - MINIO_ROOT_USER=minioadmin
   - MINIO_ROOT_PASSWORD=miniopassword
  volumes:
   - minio_data:/data
 
 minio-mc:
  image: minio/mc:latest
  volumes:
   - minio_data:/data
  tty: true
  stdin_open: true
  network_mode: "host"
  
volumes:
 minio_data:
 
