apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hello-minikube
  name: as-sharp-as-marble
  namespace: ns
spec:
  containers:
  - image: k8s.gcr.io/echoserver:1.10
    name: as-sharp-as-marble
    ports:
    - containerPort: 8081
      protocol: TCP
subjects:
  kind: ServiceAccount
  name: default
  namespace: portainer
